# name: TestPROGPOE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List contents
        run: ls

      - name: compile classes
        working-directory: ./src
        run: javac -cp "../testresoureces/junit-platform-console-standalone-1.6.0.jar" ./login/Login.java ./login/LoginDetail.java "../test/login/LoginTest.java" "../test/login/LoginDetailTest.java" ./login/Task.java ./login/TO_DO_LIST.java "../test/login/TaskTest.java" "../test/login/TO_DO_LISTTest.java"

      - name: List contents of src directory after compile
        working-directory: ./src/login
        run: ls

      - name: copy compiled classes to testresources directory
        working-directory: ./src/login
        run: cp Task.class Login.class LoginDetail.class TO_DO_LIST.class ../../test/Login/

      - name: copy compiled Test classes to testresources directory
        working-directory: ./test/login
        run: cp LoginTest.class LoginDetailTest.class TaskTest.class TO_DO_LISTTest.class ../../testresources/

      - name: List contents test package
        working-directory: ./test/login
        run: ls

      - name: run TO_DO_LIST Class tests and create report
        working-directory: ./test
        run: |
         ls
         java -jar "../testresoureces/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class login.TO_DO_LISTTest

      - name: run LoginDetail Class tests and create report
        working-directory: ./test
        run: |
         ls
         java -jar "../testresoureces/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class login.LoginDetailTest
